name: GitHub Script for PHP
description: Run simple ruby scripts
branding:
  color: purple
  icon: code
inputs:
  script:
    description: The script to run
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false    
  php-version:
    description: Version of PHP to use.
    default: latest
    required: false
runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/action.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_SCRIPT: ${{ inputs.script }}
        INPUT_PHP_VERSION: ${{ inputs.php-version }}
