name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-script:
    name: 'Run `script`'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          script: |
            echo "hello\n";
